
---
#  PLN with offsets and covariates

- Cell-line effect is in the regression coefficient (groupwise or common mean)
- Spurious effect regarding the interactions between genes (full or diagonal covariance).

## Offset: .small[modeling sampling effort]

The predefined offset uses the total sum of reads.

```{r simple PLN offsets, cache = TRUE, results = FALSE}
M01_scRNA <- PLN(counts ~ 1 + offset(log(total_counts)), scRNA_train)
M02_scRNA <- PLN(counts ~ 1 + offset(log(total_counts)), scRNA_train,
                 control = PLN_param(covariance = "diagonal"))
```

## Covariates: .small[cell-line effect ('ANOVA'-like) ]

The `cell_line` is a natural candidate for explaining a large of the variance.

```{r PLN covariate cell_line, cache = TRUE, results = FALSE}
M11_scRNA <- PLN(counts ~ 0 + cell_line + offset(log(total_counts)), scRNA_train)
M12_scRNA <- PLN(counts ~ 0 + cell_line + offset(log(total_counts)), scRNA_train,
                 control = PLN_param(covariance = "diagonal"))
```

---
#  PLN with offsets and covariates (2)

There is a clear gain in introducing the cell_line covariate in the model:

```{r PLN covariate oaks results, echo = TRUE}
rbind(M01 = M01_scRNA$criteria, M02 = M02_scRNA$criteria, 
      M11 = M11_scRNA$criteria, M12 = M12_scRNA$criteria) %>% 
  knitr::kable(format = "html")
```

---
#  PLN with offsets and covariates (3)

Looking at the coefficients $\mathbf{B}$ associated with `cell_line` bring additional insights:

```{r scRNA matrix plot, fig.width=6, fig.height=6, echo = FALSE, fig.align='center'}
heatmap(coef(M12_scRNA))
```

---
# Simple torch example in `R` 

```{r, cache.rebuild=TRUE,  torch-vs-nlopt}
data("oaks")
system.time(myPLN_torch <-
              PLN(Abundance ~ 1  + offset(log(Offset)),
                  data = oaks, control = PLN_param(backend = "torch", trace = 0)))
system.time(myPLN_nlopt <-
              PLN(Abundance ~ 1  + offset(log(Offset)),
                  data = oaks, control = PLN_param(backend = "nlopt", trace = 0)))
```

```{r}
myPLN_torch$loglik
myPLN_nlopt$loglik
```

